[book]
authors = ["nikki9750"]
language = "ja"
multilingual = false
src = "src"
title = "Notepad.md"

[preprocessor.pagetoc]
[preprocessor.alerts]
[preprocessor.katex]
[preprocessor.mermaid]
command = "mdbook-mermaid"

after = ["links"]

[output.html.playground]
editable = true

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js", "theme/mermaid.min.js", "theme/mermaid-init.js"]
git-repository-url = "https://github.com/tam1192/tam1192"
default-theme = "light"
preferred-dark-theme = "navy"